language: ruby

cache:
  bundler: true
  directories:
    - 'spec/fixtures/puppet_controlrepo/.onceover' # Onceover cache

script: bundle exec rake full_tests

matrix:
  include:
    # 2016.x -> 2017.2
    - rvm: 2.1.9
      env: PUPPET_VERSION="~>4.0"
      bundler_args: --path vendor/bundle --without acceptance
    
    # 2017.3 -> 2018.1
    - rvm: 2.4.4
      env: PUPPET_VERSION="~>5.0"
      bundler_args: --path vendor/bundle --without acceptance
    
    # 2019.0 -> now
    - rvm: 2.5.1
      env: PUPPET_VERSION="~>6.0"
      bundler_args: --path vendor/bundle
      
    